#!/bin/bash

# Quick Test Execution Guide
# This script shows common test commands

echo "=========================================="
echo "MMV Freelance API - Test Quick Reference"
echo "=========================================="
echo ""

echo "📝 Available Test Commands:"
echo ""
echo "1. Run ALL tests:"
echo "   node tests/run-all-tests.js"
echo ""
echo "2. Run Auth tests (registration & login):"
echo "   node tests/test-auth.js"
echo ""
echo "3. Run User routes tests:"
echo "   node tests/test-user-routes.js"
echo ""
echo "4. Run Client routes tests:"
echo "   node tests/test-client-routes.js"
echo ""
echo "5. Run Videographer routes tests:"
echo "   node tests/test-videographer-routes.js"
echo ""
echo "6. Run Video Editor routes tests:"
echo "   node tests/test-videoeditor-routes.js"
echo ""
echo "⚙️  With Configuration:"
echo ""
echo "   Verbose output:"
echo "   VERBOSE=true node tests/run-all-tests.js"
echo ""
echo "   Show full responses on failures:"
echo "   SHOW_FULL_RESPONSE=true node tests/test-auth.js"
echo ""
echo "   Different API URL:"
echo "   TEST_BASE_URL=http://localhost:3000 node tests/run-all-tests.js"
echo ""
echo "⚠️  Prerequisites:"
echo "   - Server must be running (npm run dev)"
echo "   - Database must be accessible"
echo "   - Port 8000 must be available"
echo ""
echo "=========================================="
